---
- name: creation of multiple user and files
  hosts: all
  tasks:
   - name: creation of users
     user:
      name: "{{item.name}}"
      password: "{{item.password}}"
      home: "{{item.home}}"
     with_items:
      - {name: alex, password, home: /home/ubuntu/}
      - {name: bibhu, password, home:  /home/ubuntu/}       
