---
- name: error handling
  hosts: all
  tasks:
   - block:
      - name: install tomcat7
        apt:
         name: tomcat7
         state: latest
     rescue:
       - name: install tomcat 8
         apt:
          name: tomcat8
          state: latest
          update_cache: yes 
     always: 
       - name: restart tomcat 8
         service:
          name: tomcat8
          state: restarted 
