---
- name: create a  user and display the output
  hosts: server
  tasks:
   - name: create a user
     user:
      name: rajesh
      password: host
     register: op 
   - name: display out
     debug: 
      var: op
