---
- name: install apache2 and chnage home page
  hosts: all
  tasks:
   - name: install apache2
     apt:
      name: apache2
      state: present
   - name: change home page
     copy:
      content: "I love you baby\n"
      dest: /var/www/html/index.html
   - name: restart apache2
     service:
      name: apache2
      state: restarted

